version: 1

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
    null:
        class: logging.NullHandler
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
    file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: 'bfkac.log'
        mode: 'a'
        encoding: 'utf-8'

loggers:
    bfkac:
        level: DEBUG
        handlers:
            - file

root:
    level: ERROR
    handlers:
        - console
